from __future__ import annotations

from datetime import date, datetime
from pathlib import Path
import yaml

from ..config import load_config, load_life_model
from ..db import get_connection, get_todays_tasks, get_score

def sync_to_obsidian():
    """Sync today's status to the configured Obsidian vault."""
    config = load_config()
    vault_path_str = config.get("obsidian", {}).get("vault_path")
    if not vault_path_str:
        return False
    
    vault_path = Path(vault_path_str).expanduser().resolve()
    if not vault_path.exists():
        return False
    
    daily_notes_dir = vault_path / "SelfHeal" / "Daily"
    daily_notes_dir.mkdir(parents=True, exist_ok=True)
    
    today = date.today()
    note_path = daily_notes_dir / f"{today.isoformat()}.md"
    
    content = generate_daily_report(today)
    
    with open(note_path, "w") as f:
        f.write(content)
    
    return True

def generate_daily_report(target_date: date) -> str:
    """Generate a markdown report for the given date."""
    conn = get_connection()
    tasks = get_todays_tasks(conn, target_date.isoformat())
    score_data = get_score(conn, target_date.isoformat())
    conn.close()
    
    lines = [
        f"# SelfHeal Daily Report - {target_date.strftime('%A, %B %d, %Y')}",
        "",
        "## Summary",
    ]
    
    if score_data:
        sc = score_data['score']
        mood = "On Track" if sc >= 70 else "Recovering" if sc >= 40 else "Needs Focus"
        lines.extend([
            f"- **Mood:** {mood}",
            f"- **Overall Score:** {sc:.0f}/100",
            f"  - Task Completion: {score_data['task_completion']}/40",
            f"  - Time Utilization: {score_data['time_utilization']}/30",
            f"  - Goal Alignment: {score_data['goal_alignment']}/20",
            f"  - Consistency Bonus: {score_data['consistency_bonus']}/10",
        ])
    else:
        lines.append("- *No score data available yet.*")
        
    model = load_life_model()
    if model:
        energy = model.get("energy", {})
        sleep = model.get("sleep", {})
        lines.extend([
            "",
            "## Life Model Context",
            f"- **Sleep Window:** {sleep.get('wake', '--:--')} - {sleep.get('bed', '--:--')}",
            f"- **Energy Peaks:** {energy.get('peak', 'N/A')}",
            f"- **Energy Lows:** {energy.get('low', 'N/A')}",
        ])
        
    lines.extend([
        "",
        "## Tasks",
        "| Status | Time | Task | Priority |",
        "| :--- | :--- | :--- | :--- |",
    ])
    
    for t in tasks:
        status_icon = "✅" if t.get("status") == "done" else "⏳"
        time_range = f"{t.get('scheduled_start', '--:--')} - {t.get('scheduled_end', '--:--')}"
        task_name = f"{t.get('emoji', '')} {t.get('name', '')}".strip()
        priority = t.get("priority", "medium")
        lines.append(f"| {status_icon} | {time_range} | {task_name} | {priority} |")
        
    lines.extend([
        "",
        "---",
        "*Generated by SelfHeal*",
    ])
    
    return "\n".join(lines)


def save_interview_to_obsidian(messages: list[dict[str, str]], model: dict[str, Any] | None = None) -> bool:
    """Save an interview transcript to Obsidian."""
    config = load_config()
    vault_path_str = config.get("obsidian", {}).get("vault_path")
    if not vault_path_str:
        return False
    
    vault_path = Path(vault_path_str).expanduser().resolve()
    if not vault_path.exists():
        return False
    
    interviews_dir = vault_path / "SelfHeal" / "Interviews"
    interviews_dir.mkdir(parents=True, exist_ok=True)
    
    today = date.today()
    timestamp = datetime.now().strftime("%H-%M-%S")
    note_path = interviews_dir / f"Interview_{today.isoformat()}_{timestamp}.md"
    
    lines = [
        f"# SelfHeal Interview - {today.isoformat()}",
        "",
        "## Summary",
        f"- **Date:** {today.isoformat()}",
        f"- **Model Version:** {model.get('version', '1.0') if model else 'N/A'}",
        "",
        "## Transcript",
        "",
    ]
    
    for m in messages:
        role = m["role"].capitalize()
        content = m["content"]
        if role == "System":
            continue
        lines.append(f"### {role}")
        lines.append(content)
        lines.append("")
        
    if model:
        lines.extend([
            "---",
            "## Resulting Life Model",
            "```yaml",
            yaml.dump(model, default_flow_style=False),
            "```",
        ])
        
    with open(note_path, "w") as f:
        f.write("\n".join(lines))
    
    return True
