from __future__ import annotations

from datetime import date
from pathlib import Path

from ..config import load_config
from ..db import get_connection, get_todays_tasks, get_score

def sync_to_obsidian():
    """Sync today's status to the configured Obsidian vault."""
    config = load_config()
    vault_path_str = config.get("obsidian", {}).get("vault_path")
    if not vault_path_str:
        return False
    
    vault_path = Path(vault_path_str).expanduser().resolve()
    if not vault_path.exists():
        return False
    
    daily_notes_dir = vault_path / "SelfHeal" / "Daily"
    daily_notes_dir.mkdir(parents=True, exist_ok=True)
    
    today = date.today()
    note_path = daily_notes_dir / f"{today.isoformat()}.md"
    
    content = generate_daily_report(today)
    
    with open(note_path, "w") as f:
        f.write(content)
    
    return True

def generate_daily_report(target_date: date) -> str:
    """Generate a markdown report for the given date."""
    conn = get_connection()
    tasks = get_todays_tasks(conn, target_date.isoformat())
    score_data = get_score(conn, target_date.isoformat())
    conn.close()
    
    lines = [
        f"# SelfHeal Daily Report - {target_date.strftime('%A, %B %d, %Y')}",
        "",
        "## Summary",
    ]
    
    if score_data:
        lines.extend([
            f"- **Score:** {score_data['score']:.0f}/100",
            f"- **Task Completion:** {score_data['task_completion']}/40",
            f"- **Time Utilization:** {score_data['time_utilization']}/30",
            f"- **Goal Alignment:** {score_data['goal_alignment']}/20",
            f"- **Consistency Bonus:** {score_data['consistency_bonus']}/10",
        ])
    else:
        lines.append("- *No score data available yet.*")
        
    lines.extend([
        "",
        "## Tasks",
        "| Status | Time | Task | Priority |",
        "| :--- | :--- | :--- | :--- |",
    ])
    
    for t in tasks:
        status_icon = "✅" if t.get("status") == "done" else "⏳"
        time_range = f"{t.get('scheduled_start', '--:--')} - {t.get('scheduled_end', '--:--')}"
        task_name = f"{t.get('emoji', '')} {t.get('name', '')}".strip()
        priority = t.get("priority", "medium")
        lines.append(f"| {status_icon} | {time_range} | {task_name} | {priority} |")
        
    lines.extend([
        "",
        "---",
        "*Generated by SelfHeal*",
    ])
    
    return "\n".join(lines)
